### ISSUE TITLE
"name of me as text" not working properly when bundled as an app

### ISSUE THREAD

**Issue by iveney** [pjv/open-in-sublime#9]
It returns "open folder in sublime" regardless how you change the app name, because it reads the `Bundle Name` from `Info.plist` in the app package.

To fix this, either change "name of me as text" to "name of current application as text", or change the `Bundle Name` itself.

**Comment by pjv** [comment]
guess i've become a little slow as i'm not really using this puppy anymore...

merged the PR, finally.
